# Generated by Django 4.2.2 on 2023-06-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_video_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='audio',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/video-2023-06-19 05:21:00.691140'),
        ),
    ]
