# Generated by Django 4.2.2 on 2023-06-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_video_video_uuid_alter_video_durations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/video-2023-06-19 05:28:30.367534'),
        ),
    ]
