# Generated by Django 4.2.2 on 2023-06-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/video-19/06/2023 05:31:34'),
        ),
    ]
