# Generated by Django 4.2.2 on 2023-06-19 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplay',
            name='img',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images-None'),
            preserve_default=False,
        ),
    ]
