# Generated by Django 4.2.2 on 2023-06-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_multiplay_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multiplay',
        ),
    ]
